stages:
  - build
  - deploy_staging

build_app:
  image: node:14.17
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    name: yourcare-frontend-build
    paths:
      - build
  only:
    - develop

staging:
  image: node:14.17-alpine
  stage: deploy_staging
  script:
    - apk add --no-cache openssh
    - apk add --update bash
    - apk add --update git
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$STAGING_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 700 ~/.ssh
    - echo "$STAGING_SSH_PRIVATE_KEY" | tr -d '\r' > ./deploy.key
    - chmod 600 ./deploy.key
    - npm list -g pm2 || npm i -g pm2
    - pm2 deploy ecosystem.config.js staging
  only:
    - develop
